### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by carsakiller** [LuaLS/lua-language-server-rust#1]
I have just built from source on Ubuntu 22.04 x86_64, and I get many warnings during build, which seem to be present in the [CI job](https://github.com/LuaLS/lua-language-server-rust/actions/runs/10860424275/job/30141000992#step:4:129).

Worse, it seems to not function correctly, reporting an error when running the binary:

```bash
$ ./lua-language-server
Error: ExternalError(Os { code: 2, kind: NotFound, message: "No such file or directory" })
```

**Comment by CppCXY** [comment]
Because it must run publish script, the executable file and resources need to be packaged together through the publish script. I'm not sure if there is a mature solution in Rust, so I chose to write a shell script to handle this:
```bash
./publish/UnixPublish.sh
```

**Comment by CppCXY** [comment]
The complete package structure looks like this.
![image](https://github.com/user-attachments/assets/de236c7f-2f43-43b3-8759-cbaa07686f89)

**Comment by carsakiller** [comment]
I see, I thought the build step embedded the resources in the binary. After moving `dist/` over to replace the `server/bin` folder in my VS Code client, it started working for VS Code! I had to also copy over my `meta` definitions from `vscode-client/server/meta` to `vscode-client/server/bin/resources/meta` in order to get the definitions for everything, but it seems to work just fine!

This makes me wonder, how hard would it be to add HTTPS support to this Rust runtime? It could allow the addon manager to be built into the language server in Lua. Perhaps it is best as an optionally installed tool, though.

I also wonder if some of the hardest jobs like the AST parsing could be done in Rust to increase performance.

**Comment by CppCXY** [comment]
Referencing [my project](https://github.com/CppCXY/luap), I have completed the tool for managing packages through GitHub. If you only want to use just one project, these two projects can be merge easily.

**Comment by CppCXY** [comment]
As for performance, if we really want to fully improve its performance, I think switching to LuaJIT as the runtime might be an easier choice. It might be difficult for the previous implementation based on bee.lua, but not too hard for this project. It just requires modifying a few features that use Lua 5.4. However, if we do this, we won't be able to easily migrate to LuaLS 4.0. As for considering a complete implementation in Rust, I would prefer a complete rewrite of the language server.

**Comment by CppCXY** [comment]
I have completed the initial migration to LuaJIT. You can try switching to the LuaJIT branch to experience it.

**Comment by yggdr** [comment]
Where is those `resources` or `dist` folders coming from? I cannot seem to get get the langserver to work.

**Comment by CppCXY** [comment]
> Where is those `resources` or `dist` folders coming from? I cannot seem to get get the langserver to work.

I removed these directories, and now the code layout is exactly the same as LuaLS. You can download it directly from the release.

**Comment by yggdr** [comment]
Ah, I see. I now just put those files in ~/.cargo to make it work, but that sort of clobbers that directory up with stuff that doesn't seem to belong there. Is there an alternative for that?

**Comment by CppCXY** [comment]
> Ah, I see. I now just put those files in ~/.cargo to make it work, but that sort of clobbers that directory up with stuff that doesn't seem to belong there. Is there an alternative for that?

use my new project: https://github.com/CppCXY/emmylua-analyzer-rust

This is a fully Rust-implemented language server, with 10 times the performance and 10 times less memory usage.

**Comment by yggdr** [comment]
On first try, that seems to work quite nicely, thank you!
